name: Bug Report
description: Submit a bug report.
title: "[BUG]: "
labels: ["bug"]
projects: ["spe-upb/2024-CircularMarketplaces"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for filling out a bug report form for ReList. To help us identify and fix the issue, please fill out the following information.
  - type: markdown
    attributes:
      value: |
        Please add all relevant issue metadata. This includes: assignees, labels, milestone and relevant branches/pull requests.
  - type: textarea
    id: bug-description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is.
      placeholder: Describe the bug here.
    validations:
      required: true
  - type: textarea
    id: reproduction-steps
    attributes:
      label: Reproduction Steps
      description: Steps to reproduce the behaviour.
      placeholder: Steps to reproduce the behaviour.
    validations:
      required: true
  - type: textarea
    id: expected-behaviour
    attributes:
      label: Expected Behaviour
      description: A clear and concise description of what you expected to happen.
      placeholder: Describe what you expected to happen.
    validations:
      required: true
  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: Please provide information about your environment. For example, your operating system, browser, and any other relevant information.
      placeholder: Information about your environment.
  - type: textarea
    id: additional-information
    attributes:
      label: Additional Information
      description: Add any other context about the problem here.
      placeholder: Add any other context about the problem here.
    validations:
      required: false