name: Node.js CI

on:
  push:
    branches:
    - "dev"
  pull_request:
    branches: [ "dev" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: app/backend/package-lock.json  # Adjusted path

    - name: Install dependencies
      run: npm ci
      working-directory: app/backend
      
    - name: Build the app
      run: npm run build --if-present
      working-directory: app/backend

    - name: Run tests
      run: npm test
      working-directory: app/backend
