name: Deploy to AWS Lambda

on:
  push:
    branches:
      - dev
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install AWS CLI
        run: |
          sudo apt update
          sudo apt install -y awscli

      - name: Zip Lambda Function Code
        run: |
          cd app/backend
          zip -r ../../lambda-app.zip . -x "*.git*" "*.log*" "*.env*"

      - name: Deploy to AWS Lambda
        run: |
          aws lambda update-function-code \
            --function-name relist-backend \
            --zip-file fileb://lambda-app.zip \
            --region eu-west-1
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID_2 }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY_2 }}
