name: Deploy to AWS S3

on:
  push:
    branches:
      - dev  # Existing trigger for dev branch
      - CDTest  # Add other branches here for testing
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: dev

      - name: Set Environment Variables
        run: |
          echo "REACT_APP_FIREBASE_API=${{ secrets.REACT_APP_FIREBASE_API }}" >> $GITHUB_ENV
          echo "REACT_APP_FIREBASE_APP_ID=${{ secrets.REACT_APP_FIREBASE_APP_ID }}" >> $GITHUB_ENV

      - name: Install Node.js and Dependencies
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Dependencies
        run: npm install

      - name: Build Frontend
        run: |
          cd app/frontend
          npm run build

      - name: Configure AWS Credentials (Primary)
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-1

      - name: Deploy to S3 (Primary)
        run: aws s3 sync ./build s3://relistserver --delete

      - name: Invalidate CloudFront Cache
        run: |
          aws cloudfront create-invalidation --distribution-id E2XRTWCIX87N --paths "/*"

      - name: Deployment Completed
        run: echo "Deployment to S3 Primary and CloudFront invalidation completed!"
