name: Node.js CI

on:
  push:
    branches:
      - "dev"
  pull_request:
    branches: [ "dev" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          cache-dependency-path: app/frontend/package-lock.json

      - name: Install dependencies
        run: npm ci
        working-directory: app/frontend

      - name: Build the app
        run: CI=false npm run build --if-present
        working-directory: app/frontend


      - name: Run tests
        run: npm test
        working-directory: app/frontend
